# How to add and subtract between matrices

In [1]:
## How to add and subtract between matrices
def Kickstarter_Example_19(): 
    print()
    print(format('How to add and subtract between matrices', '*^72'))    
    
    # Load library
    import numpy as np
    
    # Create two vectors
    matrixA = np.array([[2, 3, 23],
                       [5, 6, 25],
                       [8, 9, 28]])
    matrixB = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
    # Add two matrices
    print(); print(np.add(matrixA, matrixB))
    
    # Subtract two matrices
    print(); print(np.subtract(matrixA, matrixB))

Kickstarter_Example_19()


****************How to add and subtract between matrices****************

[[ 3  5 26]
 [ 9 11 31]
 [15 17 37]]

[[ 1  1 20]
 [ 1  1 19]
 [ 1  1 19]]
